### ISSUE TITLE
Incorporate Huff Review

### ISSUE THREAD

**Issue by katyhuff** [arfc/2021-bachmann-epjn#2]
Looking good. 

The only critical one is the acknowledgements (I'm not funded by those things anymore. Best to acknowledge that the department is funding @munkm , but please do not list anything regarding my funding.) 

Other edits in the pdf.

[main.pdf](https://github.com/arfc/2021-bachmann-epjn/files/6822602/main.pdf)

**Comment by munkm** [comment]
These comments were addressed in arfc/2021-bachmann-epjn#1 so I believe we can close out this issue now.
